- hosts: all
  become: yes
  roles:
  - role: bngsudheer.centos_base
      centos_base_enable_epel: true
      centos_base_basic_packages: true
      centos_base_secure_sshd: true
      centos_base_basic_vim_tweaks: true
      centos_base_htop_configuration: true
      centos_base_fail2ban_configuration: true
      centos_base_selinux_packages: true
  post_tasks:
  - name: Install Packages
    yum: name={{ item }} state=present
    with_items:
    - nano
    - zsh
    - wget
    - git
