- src: https://github.com/bngsudheer/ansible-role-redmine.git
  scm: git
  version: 'master'

- src: https://github.com/bngsudheer/ansible-role-centos_base.git
  scm: git
  version: 'master'

- src: https://github.com/jdauphant/ansible-role-nginx.git
  scm: git
  version: 'master'

- src: https://github.com/geerlingguy/ansible-role-php.git
  scm: git
  version: 'master'

- src: https://github.com/bertvv/ansible-role-mariadb.git
  scm: git
  version: 'master'

- src: https://github.com/GROG/ansible-role-package.git
  scm: git
  version: 'master'

- src: https://github.com/kyl191/ansible-role-openvpn.git
  scm: git
  version: 'master'

- src: https://github.com/geerlingguy/ansible-role-docker.git
  scm: git
  version: 'master'

